language: java

env:
- PATH=$HOME/protoc/bin:$PATH

cache:
  directories:
  - $HOME/.m2

jdk:
- oraclejdk8
- oraclejdk10

sudo: false

script: mvn clean install cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
