apt:
  update: true

env:
- PROTOBUF_VERSION=2.6.1

before_install:
- ./install-protobuf.sh
- PATH=/home/travis/bin:$PATH protoc --version

language: java

cache:
  directories:
  - $HOME/.m2

jdk:
- oraclejdk8
- oraclejdk10

sudo: false

script: mvn clean install
