language: java

env:
- PATH=$HOME/protoc/bin:$PATH

install:
- curl -L https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip -o /tmp/protoc.zip
- unzip /tmp/protoc.zip -d "$HOME"/protoc
- mkdir -p "$HOME"/src && ln -s "$HOME"/protoc "$HOME"/src/protobuf

cache:
  directories:
  - $HOME/.m2

jdk:
- oraclejdk8

sudo: false

scipt: mvn clean install
